site_name: Desarrollo de Interfaces
nav:
  - "Inicio": "index.md"
  - "UT 1: Desarrollo de Interfaces de Usuario. Usabilidad": 
    - "1. Introducción a la Usabilidad": "ut1-desarrollodeinterfacesdeusuario-usabilidad/1introduccionalausabilidad.md"
    - "2. Diseño Centrado en el Usuario (DCU)": "ut1-desarrollodeinterfacesdeusuario-usabilidad/2diseñocentradoenelusuario.md"
    - "3. Principios de Usabilidad": "ut1-desarrollodeinterfacesdeusuario-usabilidad/3principiosdeusabilidad.md"
    - "4. Patrones de Diseño de Interfaces": "ut1-desarrollodeinterfacesdeusuario-usabilidad/4patronesdediseñodeinterfaces.md"
    - "5. Evaluación Heurística": "ut1-desarrollodeinterfacesdeusuario-usabilidad/5evaluacionheuristica.md"
    - "6. Interfaces Multidispositivo": "ut1-desarrollodeinterfacesdeusuario-usabilidad/6interfacesmultidispositivo.md"
    - "7. Elementos de Interacción en interfaces": "ut1-desarrollodeinterfacesdeusuario-usabilidad/7elementosdeinteraccioneninterfaces.md"
    - "8. Flujos de Usuario": "ut1-desarrollodeinterfacesdeusuario-usabilidad/8flujosdeusuario.md"
    - "9. Prototipado y Wireframing": "ut1-desarrollodeinterfacesdeusuario-usabilidad/9prototipadoywireframing.md"
    - "10. Accesibilidad en Interfaces de Usuario": "ut1-desarrollodeinterfacesdeusuario-usabilidad/10accesibilidadeinterfacesdeusuario.md"
  - "UT2: Introducción a TypeScript":
    - "1. ¿Qué es TypeScript?": "ut2-introduccionatypescript/1queestypescript.md"
    - "2. Ventajas de usar TypeScript": "ut2-introduccionatypescript/2ventajasdeusartypescript.md"
    - "3. Instalación y Configuración de TypeScript": "ut2-introduccionatypescript/3instalacionyconfiguraciondetypescript.md"
    - "4. Primer Proyecto con TypeScript": "ut2-introduccionatypescript/4primerproyecto.md"
    - "5. Tipos Básicos en TypeScript": "ut2-introduccionatypescript/5tiposbasicos.md"
    - "6. Condicionales en TypeScript": "ut2-introduccionatypescript/6condicionales.md"
    - "7. Bucles en TypeScript": "ut2-introduccionatypescript/7bucles.md"
    - "8. Objetos en TypeScript": "ut2-introduccionatypescript/8objetos.md"
    - "9. Funciones y parámetros en TypeScript": "ut2-introduccionatypescript/9funcionesyparametros.md"
    - "10. Interfaces y Tipos personalizados en TypeScript": "ut2-introduccionatypescript/10interfacesyobjetos.md"
    - "11. Clases y Herencia en TypeScript": "ut2-introduccionatypescript/11clasesyherencia.md"
    - "12. Modularización de código en TypeScript": "ut2-introduccionatypescript/12modularizaciondecodigo.md"
    - "Recursos y FAQ": "ut2-introduccionatypescript/13recursos.md"
  - "UT3: Introducción a Angular":
    - "1. ¿Qué es Angular?": "ut3-introduccionaangular/1introduccion.md"
    - "2. Conceptos Básicos de Angular": "ut3-introduccionaangular/2conceptosbasicos.md"
    - "3. Ruteo y navegacion": "ut3-introduccionaangular/3ruteoynavegacion.md"
    - "4. Gestión del estado y comunicación entre componentes": "ut3-introduccionaangular/4comunicacionentrecomponentes.md"
    - "5. Formularios": "ut3-introduccionaangular/5formularios.md"
    - "6. Consumo de APIs y Manejo de HTTP": "ut3-introduccionaangular/6consumodeapis.md"
    - "7. Pipes y filtros": "ut3-introduccionaangular/7pipesyfiltros.md"
    - "8. Recursos y FAQ": "ut3-introduccionaangular/8recursosyfaq.md"
    - "9. Explicación del proyecto Todo-List": "ut3-introduccionaangular/9explicacionproyectotodolist.md"
  - "UT4: Creación y Manejo de Componentes con Angular-Ionic":
    - "1. Introducción a Angular-Ionic": "ut4-angular-ionic/1introduccion.md"
    - "2. Desarrollo de Galería de Fotos":
      - "2.1. Creación de la app e inicialización ": "ut4-angular-ionic/2creacionprimeraapp/21creaciondelaappeinicialización.md"
      - "2.2. Toma de fotos": "ut4-angular-ionic/2creacionprimeraapp/22tomadefotos.md"
      - "2.3. Guardado de fotos": "ut4-angular-ionic/2creacionprimeraapp/23guardadodefotos.md"
      - "2.4. Carga de fotos del sistema": "ut4-angular-ionic/2creacionprimeraapp/24cargadefotosdelsistema.md"
      - "2.5. Añadiendo la versión móvil": "ut4-angular-ionic/2creacionprimeraapp/25versionmovil.md"
      
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
plugins:
  - search:
      lang: es
  - glightbox

theme:
  name: material
  features:
    - navigation.footer
    - navigation.path
  palette:
    - scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Quitar modo oscuro
extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-3VWRJDCQS9
    feedback:
      title: <a href='https://ko-fi.com/jgarciadeparedesh02' title='Invítame a un café en ko-fi.com' target='_blank'><img height='36' style='border:0px;height:36px;' src='https://storage.ko-fi.com/cdn/kofi2.png?v=3' border='0' alt='Invítame a un café en ko-fi.com' /></a>
      ratings:
        - icon: material/emoticon-happy-outline
          name: Esta página es genial
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: Podría mejorar
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.